08.03.20   13:58:08 - moduls - ERROR - ERROR on logging form
Traceback (most recent call last):
  File "C:\Users\ART\5\instagram_bot\py_raw\moduls.py", line 77, in logging_in
    not_now_btn[-1].click()
IndexError: list index out of range
08.03.20   13:58:32 - moduls - ERROR - ERROR on logging form
Traceback (most recent call last):
  File "C:\Users\ART\5\instagram_bot\py_raw\moduls.py", line 77, in logging_in
    not_now_btn[-1].click()
IndexError: list index out of range
08.03.20   14:44:05 - moduls - ERROR - [Errno 2] No such file or directory: './../dats/group_linkss.yaml'
08.03.20   15:36:30 - moduls - ERROR - 'animation'
08.03.20   15:40:22 - moduls - ERROR - 'animation'
08.03.20   17:25:48 - moduls - ERROR - 'NoneType' object has no attribute 'click'
08.03.20   21:09:08 - moduls - ERROR - 'belka_color'
08.03.20   21:42:16 - moduls - ERROR - Message: chrome not reachable
  (Session info: chrome=80.0.3987.132)

09.03.20   09:50:43 - moduls - ERROR - 'all_followers'
